---
title: "Example 4"
output: html_document
---

## Example 4

```{r}
library(ideogRam)
```

```{r}
ideo_04_config <- list(
                       organism = "banana",
                       orientation = "horizontal",
                       ploidy = 3,
                       chrMargin = 10,
                       ancestors = list(
                           "A" = "#dea673",
                           "B" = "#7396be"
                       ),
                       ploidyDesc = c(
                                    'AAB',
                                    'AAB',
                                    'BAB',
                                    'AAB',
                                    'AAB',
                                    'BBB',
                                    'AAB',
                                    'AAB',
                                    'AAB',
                                    'AAB',
                                    'AAB'
                                    ),
                       rangeSet = list(list(
                           chr = 1,
                           ploidy = c(0, 1, 0),
                           start = 17120000,
                           stop = 25120000,
                           color = c(0, '#7396be', 0)
                       ), list(
                           chr = 2,
                           ploidy = c(0, 1, 1),
                           start = 12120000,
                           stop = 15120000,
                           color = c(0, '#7396be', '#dea673')
                       ))
)

p <- ideogRam(data = ideo_04_config)
p
```

