---
title: "Examples"
output: html_document
---

Some examples of the package.

```{r}
library(ideogRam)
```


## Example 1

```{r}
ideo_01_config <- list(
    organism = "human",
    orientation = "horizontal",
    annotations = list(
        list(
            name = "xxx",
            chr = "2",
            start = 34294,
            stop = 125482
        ),
        list(
            name = "BRCA1",
            chr = "17",
            start = 43125400,
            stop = 43125482
        )
    )
)
p <- ideogRam(ideo_01_config)
p
```

```{r eval=FALSE, include=FALSE}
htmlwidgets:::toJSON(ideo_01_config)
jsonlite::toJSON(ideo_01_config)
```

```{r eval=FALSE, include=FALSE}
htmlwidgets::saveWidget(p, "~/github/ideogRam/example/basic.html", selfcontained = FALSE)
```


## Example 2

```{r}
annotationTracks <- list(
    list("id" = "pathogenicTrack", "displayName" = "Pathogenic", "color" = "#F00"),
    list("id" = "uncertainSignificanceTrack", "displayName" = "Uncertain significance", "color" = "#CCC"),
    list("id" = "benignTrack", "displayName" = "Benign", "color" = "#8D4")
)

ideo_02_config <- list(
    organism = "human",
    orientation = "horizontal",
    chrWidth = 8,
    annotationsPath = "/annotations_tracks_files/Ideogram-0.9.0/data/annotations/1000_virtual_snvs.json",
    annotationTracks = annotationTracks
)

p <- ideogRam(ideo_02_config)
p
```

## Example 3

Test native url input for annotationsPath: e.g. 
https://unpkg.com/ideogram@0.9.0/dist/data/annotations/10_virtual_cnvs.json

See https://github.com/eweitz/ideogram/issues/78

```{r}
ideo_03_config <- list(
    organism = "human",
    annotationsPath = "https://unpkg.com/ideogram@0.9.0/dist/data/annotations/10_virtual_cnvs.json",
    annotationsLayout = "overlay"
)

p <- ideogRam(data = ideo_03_config)
p
```

## Example 4

```{r}
ideo_04_config <- list(
                       organism = "banana",
                       orientation = "horizontal",
                       ploidy = 3,
                       chrMargin = 10,
                       ancestors = list(
                           "A" = "#dea673",
                           "B" = "#7396be"
                       ),
                       ploidyDesc = c(
                                    'AAB',
                                    'AAB',
                                    'BAB',
                                    'AAB',
                                    'AAB',
                                    'BBB',
                                    'AAB',
                                    'AAB',
                                    'AAB',
                                    'AAB',
                                    'AAB'
                                    ),
                       rangeSet = list(list(
                           chr = 1,
                           ploidy = c(0, 1, 0),
                           start = 17120000,
                           stop = 25120000,
                           color = c(0, '#7396be', 0)
                       ), list(
                           chr = 2,
                           ploidy = c(0, 1, 1),
                           start = 12120000,
                           stop = 15120000,
                           color = c(0, '#7396be', '#dea673')
                       ))
)

p <- ideogRam(data = ideo_04_config)
p
```

